{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "phenogram.fullname" . }}
  labels:
    {{- include "phenogram.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "phenogram.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
{{- end }}
