{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "phenogram.fullname" . }}-postgresql
  labels:
    {{- include "phenogram.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.port }}
      targetPort: postgresql
      protocol: TCP
  selector:
    {{- include "phenogram.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
